### ISSUE TITLE
Javascript in mail markup t3sbootstrap

### ISSUE THREAD

**Issue by PittRo** [in2code-de/luxletter#206] opened 2024-01-26 15:09 UTC
Typo3: 11.5.34
Extension: luxletter - TYPO3 Email Marketing Newsletter Tool	luxletter	19.2.2
Extension:  Bootstrap Components	t3sbootstrap	v5.2.8
Sample NL: https://wir.gorheinland.com/gonewsletter-ausgabe-januar-2024/
Usecase: E-Mail posting

responsible script: typo3conf/ext/t3sbootstrap/Classes/EventListener/AssetRenderer/IsInline.php
included javascript: <script src="/typo3temp/assets/t3sbootstrap_78fe5d76bf.js?1671016308"></script>

We use with t3s within our typo3 instance, if we sen emails via luxletter, fluid pharses inline CSS. therefor t3sbootstrap renders a <script... into html markup. May you help us with any option we could easyly set?

We were already looking for any option like this at /typo3/module/web/T3sbootstrapM1?id=1&tx_t3sbootstrap_web_t3sbootstrapm1%5Bconfig%5D=1&tx_t3sbootstrap_web_t3sbootstrapm1%5Baction%5D=edit&tx_t3sbootstrap_web_t3sbootstrapm1%5Bcontroller%5D=Config

**Comment by einpraegsam** [comment] 2024-01-29 09:17
This seems to be not a task for LUXletter? You should configure t3sbootstrap in a way that the JS is not included when calling a page with type `1562349004` in my eyes. Or do I missunderstood your question?

**Comment by PittRo** [comment] 2024-01-31 07:42
There is no possibiltiy to configure that. I guess your extension is definitely responsible for the parsed markup and even should validate it. 
I opened up a connector issue in there repo.

**Comment by einpraegsam** [comment] 2024-01-31 08:57
Okay, but if there is an extension that adds JS - no matter what TypeNum - this seems to be a general problem. Don't you think? 
What if you want to build an AJAX request with a special TypeNum or a print view or whatever...

**Comment by einpraegsam** [comment] 2024-02-02 11:55
I will close this issue for now. Pls reopen if it turns out, that the problem is related to LUXletter.

**Closed by einpraegsam** 2024-02-02 11:55 UTC
