### ISSUE TITLE
Sending testmail via "Send a test mail to yourself" is broken

### ISSUE THREAD

**Issue by ses2013** [in2code-de/luxletter#139] opened 2022-10-06 13:09 UTC
Can not send test mail

```
#1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "%/ajax%/luxletter%/testMail" was not found.
```

**Comment by einpraegsam** [comment] 2022-10-06 15:49
I cannot reproduce this issue. Can you tell me a bit more about your environment?
Caches are cleaned I guess?

**Comment by ses2013** [comment] 2022-10-06 17:22
I have this since and after updating from version 4.3.x Before it worked.
Composer Install of 10.4.32
Php 7.4.7

Mail Test Setup works.
Cache cleared several times.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Creating default object from empty value in /home/users/tim-typo3/htdocs/www.xxx.de/docroot/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php line 707 | TYPO3\CMS\Core\Error\Exception thrown in file /home/users/tim-typo3/htdocs/xxx.de/docroot/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 134. Requested URL: https://www.xxx.de/typo3/index.php?route=%%2Fajax%%2Fluxletter%%2FtestMail&token=--AnonymizedToken--&origin=1571&email=ses%%40xxx.de&subject=test&configuration=1&layout=CTMNewsletter

**Comment by einpraegsam** [comment] 2022-10-06 18:17
I just tested again on 10.4.32 (composer mode) with luxletter 17.0.2 and see no problems when sending testmails. 
To be sure, when you upgrade from version 4 to 17 - did you see the breaking changes and did the todos:
https://github.com/in2code-de/luxletter/blob/develop/Documentation/Changelog/Index.md#upgrade-to-5x

**Comment by einpraegsam** [comment] 2022-10-14 08:23
Any feedback?

**Comment by ses2013** [comment] 2022-10-14 10:10
I upgrade with every step necessary and since the update to 5.x.x the problem occured – as far as I can remember.
Is the URl above OK? Because when I try that in the frontend I get the error in the first post.

**Comment by ses2013** [comment] 2022-10-19 12:11
What will be shown in your enviroment when you open the link in the FE?

**Comment by einpraegsam** [comment] 2022-10-19 12:57
![testemail](https://user-images.githubusercontent.com/89055/196697147-9407341f-856c-4668-9487-7e617219f388.png)
This is the AJAX request in the browser

**Comment by einpraegsam** [comment] 2022-11-04 21:23
Any feedback for me? Otherwise I have to close this issue.

**Comment by ses2013** [comment] 2022-11-28 12:33
Sending with typo3 11.5.x 
Exact same configuration is working though!

**Closed** 2022-11-28 14:55 UTC
