### ISSUE TITLE
Error if user is deleted

### ISSUE THREAD

**Issue by jaskulsky** [in2code-de/luxletter#71] opened 2020-12-09 09:06 UTC
Hi,
if a user is deleted in db after creating the queue, there is the error
Return value of In2code\Luxletter\Domain\Model\Queue::getUser() must be an instance of In2code\Luxletter\Domain\Model\User, null returned

**Comment by einpraegsam** [comment] 2020-12-09 13:23
Can you please give me a full error message with a backtrace to this?

**Comment by jaskulsky** [comment] 2020-12-09 13:37
Core: Exception handler (CLI): Uncaught TYPO3 Exception: Return value of In2code\Luxletter\Domain\Model\Queue::getUser() must be an instance of In2code\Luxletter\Domain\Model\User, null returned | TypeError thrown in file /home/www/v9/typo3conf/ext/luxletter/Classes/Domain/Model/Queue.php in line 80

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of In2code\Luxletter\Domain\Model\Link::getUser() must be an instance of In2code\Luxletter\Domain\Model\User, null returned | TypeError thrown in file /home/www/v9/typo3conf/ext/luxletter/Classes/Domain/Model/Link.php in line 64. Requested URL: https://www.***.de/?luxletterlink=09f670de377bcb20a476a6a0d7df76af0fd374f68914abee8c7363606247e085

**Comment by einpraegsam** [comment] 2020-12-09 14:12
Thx, I just pushed a fix to develop branch. Can you confirm that this issue is fixed with it?

**Closed** 2020-12-09 14:12 UTC

**Comment by jaskulsky** [comment] 2020-12-09 14:22
Thx for the fix.
But now there is a bug in the progress queue.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getReadableName() on null | Error thrown in file /home/www/v9/typo3conf/ext/luxletter/Classes/Mail/ProgressQueue.php in line 118. Requested URL: https://www.***.de/typo3/index.php?route=%%2Fsystem%%2FtxschedulerM1%%2F&token=--AnonymizedToken--&tx_scheduler[execute][]=1

**Comment by einpraegsam** [comment] 2020-12-09 16:37
I just tested:
Added a newsletter with some users and a user with uid1
After that I deleted record fe_users.uid=1 by setting deleted=1
After that I used `./vendor/bin/typo3cms luxletter:queue 4` without a problem.

Can you please explain how I can reproduce this issue step by step?

**Comment by jaskulsky** [comment] 2020-12-10 07:41
I do not delete records with deleted=1. They are reallly deleted from the db, due to GDPR.

**Comment by einpraegsam** [comment] 2020-12-10 14:14
ok, and again I tested this without seeing any problems:
Added a newsletter with some users and a user with uid1
After that I deleted record fe_users.uid=1 completely in database
After that I used ./vendor/bin/typo3cms luxletter:queue 5 without a problem.

Can you please explain how I can reproduce this issue step by step?

**Comment by rr-it** [comment] 2021-01-05 15:04
I can reproduce the issue in production. This bugfix works for me.
I fixed a follow-up bug: https://github.com/in2code-de/luxletter/issues/74

**Comment by einpraegsam** [comment] 2021-01-10 16:02
I just merged the fix to develop. Ready for the upcoming release.
